Filter Conferences by Date Range
tech-conferences/confs.tech pull request #761
Opened 2024-09-11 17:36 UTC by JuanPabloDiaz

It's still a work in progress

- Working in the functionality. Can someone review that part please?
- I tried to make the data boxes smaller but for some reason the SCSS is not working.

reference #749

![image](https://github.com/user-attachments/assets/54a710e3-4652-4fa6-be7f-22049170dd37)

![image](https://github.com/user-attachments/assets/2d286434-bf4c-4b0a-9cf0-e735f3d9b7de)

2024-09-11 17:43 UTC, cgrail commented
Looks good. But there is a compile error

2024-09-11 17:56 UTC, JuanPabloDiaz commented
> Looks good. But there is a compile error

I finally got it lol

2024-09-13 11:19 UTC, JuanPabloDiaz commented
![image](https://github.com/user-attachments/assets/1da2a6aa-76d9-44f7-bfda-4eee708c3420)

2024-09-14 00:22 UTC, nimzco commented
Hey @JuanPabloDiaz, thank you for this proposal and this PR!

In terms of usability, how about only showing months instead of full dates in the picker? I'm even thinking, only showing one month, to be like: "show me conference after this date".

If we were to keep start and end date, I would like the filter to update as soon as I select the start date. Meaning: I don't need to select the end date to see the conference list change.
Additionally, we need to handle the mobile view, or to hide it on mobile.

2024-09-14 00:23 UTC, nimzco commented on src/scenes/ConferenceList/ConferenceList.tsx
> +      setStartDate(date)
Don't you want to handle when the user empties the input?

2024-09-14 00:25 UTC, nimzco commented on src/scenes/ConferenceList/ConferenceList.module.scss
> +  padding: 2px;
This padding breaks the vertical alignment, see:
<img width="686" alt="image" src="https://github.com/user-attachments/assets/05a7805c-3fa6-4bfa-a4f6-749807638e4e">

2024-09-14 00:26 UTC, nimzco commented on src/scenes/ConferenceList/ConferenceList.module.scss
> +  gap: 2px;
```suggestion
  gap: spacing(tight);
```

2025-01-29 03:05 UTC, JuanPabloDiaz commented on src/scenes/ConferenceList/ConferenceList.module.scss
> +  padding: 2px;
wow, I had to zoom in to see that.

Great catch! I will work on it

2025-07-09 13:20 UTC, JuanPabloDiaz commented
Hi @nimzco @cgrail, 

I am happy with how it turns out. Here is the summary of this PR:


https://github.com/user-attachments/assets/5a46559a-bacc-4b07-b866-959bb75c0487



This pull request introduces a date range filter to the Conference List page, allowing users to filter conferences by start and end dates. It also includes styling updates and minor code improvements. Below is a summary of the most important changes:

### 🎉 New! Filter conferences by date range
* Added `startDate` and `endDate` state variables to the `ConferenceListPage` component, along with handlers to manage date selection and validation (`src/scenes/ConferenceList/ConferenceList.tsx`).
* Integrated `react-datepicker` for date selection, including importing the library and its styles (`src/scenes/ConferenceList/ConferenceList.tsx`). [[1]](diffhunk://#diff-1f6136ad8af2de67937657ea7a39d0421b6bd6a7b7eea5aadfc4adb838932af3R5) [[2]](diffhunk://#diff-1f6136ad8af2de67937657ea7a39d0421b6bd6a7b7eea5aadfc4adb838932af3R46-R47)
* Updated the `ConferenceList` component to accept `startDate` and `endDate` as props and filter conferences based on the selected date range (`src/scenes/ConferenceList/components/ConferenceList/ConferenceList.tsx`). [[1]](diffhunk://#diff-7f078a98e413b2a24fdf7d94935454ce9a324d10b6c302c671edf47592f98c98R25-R26) [[2]](diffhunk://#diff-7f078a98e413b2a24fdf7d94935454ce9a324d10b6c302c671edf47592f98c98R36-R37) [[3]](diffhunk://#diff-7f078a98e413b2a24fdf7d94935454ce9a324d10b6c302c671edf47592f98c98R48-R61)

### Styling Updates
* Added styles for the date range picker and its clear button in `ConferenceList.module.scss` and `ConferenceListPage.module.scss` to ensure proper layout and responsiveness (`src/scenes/ConferenceList/ConferenceList.module.scss`, `src/scenes/ConferenceList/components/ConferenceList/ConferenceList.module.scss`). [[1]](diffhunk://#diff-c6b0d87da55110f58c80bada8613ea5797f0cf676fbd76a552594933849cca6cR89-R140) [[2]](diffhunk://#diff-e55894bde4037ea664b5c19fcf16eb2b6f689ac2a8664367b3c219d6c059be03R49-R66)

### Minor Improvements
* Added `width: 100%` to the `Search` component for better alignment and responsiveness (`src/components/Search/Search.module.scss`).
* Suppressed `prettier` warnings for certain lines in `scripts/heroku-start.js` to improve code readability without formatting conflicts.
* Added a Clear button
* Follow the responsive design
* Proper alignment of all date picker elements

2025-07-12 19:18 UTC, nimzco requested changes
A few comments, but it looks good!

When selecting a start date, I would expect the results to change. They don't until we select the end date.
We could also auto-open the end-date after selecting the start-date, but I would start filtering already.

UI:
- The height of the inputs are not the same with the search
- The X is not center-aligned.
<img width="336" height="74" alt="image" src="https://github.com/user-attachments/assets/30f71b24-c510-4bb2-a9c6-7efbf2674e78" />

2025-07-13 00:45 UTC, JuanPabloDiaz commented
Thanks for your feedback @nimzco! I've implemented your suggestions, and everything should now be working as you requested.

https://github.com/user-attachments/assets/35cfabe8-56b4-440d-a747-7f356e89a80c


feat: improve date filtering UX and fix input alignment

- Filters now apply immediately upon selecting start or end dates.
- Auto-focus end date picker for better UX  
- Fix alignment between search box and date inputs
- Enhance date range overlap detection
- Improve dark mode and accessibility

2025-07-13 13:08 UTC, nimzco commented
When testing locally, the conference list don't update anymore after I change the dates.

2025-07-13 13:43 UTC, JuanPabloDiaz commented
> When testing locally, the conference list don't update anymore after I change the dates.

Hmm, it doesn’t update when you **only** change the dates @nimzco?

It works for me when I test the date filter **alone**. I still need to work on how this new feature interacts with other filters when combined.

2025-07-13 14:07 UTC, JuanPabloDiaz commented
Thanks @nimzco! You're absolutely right. 

Date filtering was client-side while other filters were server-side, causing conflicts.

Fixed! Moved date filtering to Algolia level so it works with other filters.

Should be working now! 🎯

2025-07-14 00:12 UTC, nimzco commented on src/scenes/ConferenceList/components/ConferenceList/ConferenceList.module.scss
> +}
Are you sure all of this is needed? I don't see the CSS applied and if I remove the code, the behavior is still the same. 🤔

2025-07-14 00:13 UTC, nimzco approved these changes
Aside of my last comment. I've tested locally, and it works as expected. 🚢 
Thanks for the feature addition!

2025-07-14 01:36 UTC, JuanPabloDiaz commented on src/scenes/ConferenceList/components/ConferenceList/ConferenceList.module.scss
> +}
you are right, I forgot to remove that. I add it in this [commit](https://github.com/tech-conferences/confs.tech/pull/761/commits/b7f7af39136b2aad6fd8db91c1fb62c2007136a7) but we no longer need it.

2025-07-14 01:38 UTC, merged